ANATOMICAL_SITE_TERMS: list[tuple[str, list[str]]] = [
    ("Stomach", ["gastric"]),
    ("Pancreas", ["pancreatic"]),
    ("Liver", ["hepatic"]),
    ("Kidney", ["renal"]),
    ("Spleen", ["splenic"]),
    ("Heart", ["cardiac"]),
    ("Lung", ["pulmonary"]),
    ("Brain", ["cerebral"]),
    ("Colon", ["colonic"]),
    ("Esophagus", ["esophageal"]),
    ("Gallbladder", []),
    ("Bladder", ["vesical"]),
    ("Prostate", ["prostatic"]),
    ("Ovary", ["ovarian"]),
    ("Uterus", ["uterine"]),
    ("Breast", ["mammary"]),
    ("Thyroid", []),
    ("Skin", ["cutaneous", "dermal"]),
    ("Bone", ["osseous"]),
    ("Appendix", ["appendiceal"]),
    ("Small intestine", []),
    ("Large intestine", []),
    ("Spinal cord", []),
    ("Head", ["cranial", "cephalic"]),
    ("Face", ["facial"]),
    ("Eye", ["ocular", "orbital"]),
    ("Cheek", ["buccal"]),
    ("Ear", ["otic", "auricular"]),
    ("Nose", ["nasal"]),
    ("Chin", ["mental"]),
    ("Neck", ["cervical"]),
    ("Chest", ["thoracic"]),
    ("Abdomen", ["abdominal"]),
    ("Pubic region", ["pubic"]),
    ("Navel", ["umbilical"]),
    ("Armpit", ["axillary"]),
    ("Upper arm", ["brachial"]),
    ("Forearm", ["antebrachial"]),
    ("Wrist", ["carpal"]),
    ("Palm", ["palmar"]),
    ("Groin", ["inguinal"]),
    ("Thigh", ["femoral"]),
    ("Knee", ["patellar"]),
    ("Lower leg", ["crural"]),
    ("Ankle", ["tarsal"]),
    ("Foot", ["pedal"]),
    ("Sole", ["plantar"]),
    ("Back", ["dorsal"]),
    ("Lower back", ["lumbar"]),
    ("Buttocks", ["gluteal"]),
    ("Pelvis", ["pelvic"]),
]
